### ISSUE TITLE
Optimize package requirements in pip

### ISSUE THREAD

**Issue by PSSF23** [neurodata/ProgLearn#401]
My issue is about resolving the package requirements and possibly reversing the commits for #265. As the `pip` package does not contain `requirements.txt`, the package could not be installed properly.
#### Reproducing code example:

```bash
pip install proglearn
```

#### Error message

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/zm/vvtzm3xj241bqq0_c5xj9_v00000gn/T/pip-install-crdk0kb_/proglearn/setup.py", line 13, in <module>
    with open("requirements.txt", mode="r", encoding = "utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

#### Version information

- OS: macOS
- Python Version: 3.8.5
- Package Version: 0.0.3

**Comment by PSSF23** [comment]
@levinwil Is adding `requirements.txt` to the `pip` package possible? I am not familiar with the procedure.
