### ISSUE TITLE
XOR-RXOR tutorial breaking

### ISSUE THREAD

**Issue by latasianguy** [neurodata/ProgLearn#445]
XOR-RXOR experiment notebook breaking.

#### Reproducing code example:

```
Try running the notebook.
```

#### Error message

```
"""
Traceback (most recent call last):
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "C:\Users\shizh\Documents\GitHub\ProgLearn\docs\tutorials\functions\xor_rxor_functions.py", line 187, in experiment
    transformer_ids=[0], task_id=0)
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\proglearn-0.0.3-py3.7.egg\proglearn\progressive_learner.py", line 721, in predict
    X, transformer_ids=transformer_ids
  File "C:\Users\shizh\Anaconda3\envs\proglearn\lib\site-packages\proglearn-0.0.3-py3.7.egg\proglearn\deciders.py", line 169, in predict
    return self.classes[np.argmax(vote_overall, axis=1)]
IndexError: index 0 is out of bounds for axis 0 with size 0
"""
```

#### Version information

- Windows 10
- Python 3.7.9
- 0.0.3

**Comment by latasianguy** [comment]
Just kidding, I was on 0.0.3 instead of 0.0.4.
Will run the experiment and close issue if this works.

**Comment by latasianguy** [comment]
Checked, looks good.
